spring.application.name=bellshop

# Configuration de la base de données PostgreSQL (Flexible Prod/Local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bellshop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:arno1405}

# Le Dialecte PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration de l'Admin
bellshop.admin.username=${ADMIN_USER:admin}
bellshop.admin.password=${ADMIN_PASS:Admin123}